
install:
  - R --version
  - R -e "install.packages(c('devtools', 'covr', 'roxygen2'), Ncpus=6)"
  - R -e "if(0 < compareVersion('3.5.0', paste(R.Version()[c('major', 'minor')], collapse='.'))){ 
            source('https://bioconductor.org/biocLite.R');
            biocLite(c('BiocInstaller', 'BiocCheck'), Ncpus=6);
        } else {
            install.packages('BiocManager', Ncpus=6);
            BiocManager::install('BiocCheck', Ncpus=6);
        }"
  - R -e 'devtools::install_deps(dependencies=TRUE, Ncpus=6)'
  - R -e 'devtools::install(".", upgrade_dependencies=TRUE, dependencies=TRUE, Ncpus=6)'


language: r
sudo: required
dist: xenial
cache:
  - directories:
    - $HOME/R/Library

matrix:
  include:
    - r: bioc-release
    - r: bioc-devel
    - r: 3.5.0
    - r: 3.4.4
    - r: 3.4.2

addons:
  apt:
    packages:
      - libxml2-dev
      - tk-dev

before_install:
  - tlmgr install index marginfix bera nowidow parnotes

install:
  - R --version
  - R -q -e "
      if(0 < compareVersion('3.5.0', paste(R.Version()[c('major', 'minor')], collapse='.'))){
          if(!requireNamespace('BiocInstaller')){
              source('https://bioconductor.org/biocLite.R')
              biocLite(c('BiocInstaller'), Ncpus=6)
          }
          INSTALL <- BiocInstaller::biocLite
      } else {
          if(!requireNamespace('BiocInstaller'))
              install.packages('BiocManager', Ncpus=6)
          INSTALL <- BiocManager::install
          print(BiocManager::isDevel())
      }
      
      for(p in c('devtools', 'covr', 'roxygen2', 'BiocCheck', 'R.utils'))
          if(!requireNamespace(p, quietly=TRUE))
              INSTALL(p, Ncpus=6)
          
      R.utils::withTimeout(timeout=2400, {
          INSTALL(ask=FALSE, Ncpus=6)
          devtools::install('.', ask=FALSE, dependencies=TRUE, upgrade=TRUE)
      })
  "
  
script:
  - R CMD build .
  - R CMD BiocCheck --new-package --no-check-vignettes *tar.gz
  - R CMD check --no-vignettes --timings *tar.gz
  - R -e 'devtools::run_examples()'
  - cd vignettes && if [[ $TRAVIS_R_VERSION_STRING != "3.4.0" ]]; then
        R CMD Sweave --engine=knitr::knitr --pdf "OUTRIDER.Rnw";
    else 
        R CMD Sweave --engine=knitr::knitr --pdf "OUTRIDER.Rnw" 2>&1 | tee /dev/tty | grep Error | exit `wc -l`;
    fi

after_success:
  - Rscript -e 'covr::codecov()'

