language: r
sudo: required
dist: trusty
cache:
  - directories:
    - $HOME/python-env-OUTRIDER
    - $HOME/R/Library
    - $HOME/.cache/pip
matrix:
  include:
    - r: bioc-release
    - r: bioc-devel
    - r: 3.4

addons:
  apt:
    packages:
      - libxml2-dev
      - build-essential
      - checkinstall
      - libreadline-gplv2-dev
      - libncursesw5-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev

env:
  global:
    - REINSTALL_PYTHON="FALSE"
    - PYTHON_VERSION="3.6.5"
    - USE_PIP_AUTOCORRECTION="TRUE"

before_install:
  - tlmgr install index marginfix bera nowidow parnotes
  - if [[ $REINSTALL_PYTHON == "TRUE" ]] || ! which python${PYTHON_VERSION%.*}; then
      mkdir tmp;
      cd tmp;
      wget "https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz";
      tar xzf Python-$PYTHON_VERSION.tgz;
      cd Python-$PYTHON_VERSION;
      ./configure --enable-optimizations;
      sudo -H make altinstall;
      cd ..;
    fi 
  - if [[ $REINSTALL_PYTHON == "TRUE" ]] || [ ! -e ~/python-env-OUTRIDER/bin/activate ]; then
      python${PYTHON_VERSION%.*} -m venv --clear ~/python-env-OUTRIDER --without-pip;
      source ~/python-env-OUTRIDER/bin/activate;
      wget https://bootstrap.pypa.io/get-pip.py;
      python get-pip.py;
      deactivate;
    fi
  - source ~/python-env-OUTRIDER/bin/activate
  - pip install --upgrade pip

install:
  - pip --version
  - python --version
  - R --version
  - which pip
  - which R
  - if [[ $USE_PIP_AUTOCORRECTION == "TRUE" ]]; then
      pip3 install --upgrade autoCorrection;
    else
      pip3 install --upgrade "git+https://github.com/gagneurlab/autoCorrection.git@master";
    fi
  - R -e "BiocInstaller::biocLite(c('BiocCheck', 'covr', 'devtools'))"
  - R -e "message(BiocInstaller::isDevel())"
  - R -e 'devtools::install_deps(dependencies=TRUE, threads=4)'
  - R -e 'BiocParallel::multicoreWorkers()'
  - R -e 'devtools::install()'

script:
  - R CMD build --no-build-vignettes .
  - R CMD BiocCheck --new-package --no-check-vignettes *tar.gz
  - R CMD check --no-vignettes --timings *tar.gz
  - R CMD Sweave --engine=knitr::knitr --pdf "./vignettes/OUTRIDER.Rnw"

after_success:
  - Rscript -e 'covr::codecov()'

