language: r
sudo: required
dist: xenial
cache:
  - directories:
    - $HOME/R/Library

r:
  - bioc-release
  - bioc-devel
  - 3.5.0
  - 3.4.4
  - 3.4.2

addons:
  apt:
    packages:
      - libxml2-dev
      - tk-dev

before_install:
  - tlmgr install index marginfix bera nowidow parnotes


jobs:
  include:
    - stage: setup cache
      install:
        - R --version
        - Rscript setupEnv.R
        
    - state: test
      install:
        - R --version
        - Rscript setupEnv.R 
      script:
        - R CMD build .
        - R CMD BiocCheck --new-package --no-check-vignettes *tar.gz
        - R CMD check --no-vignettes --timings *tar.gz
      #  - R -e 'devtools::run_examples()'
      #  - cd vignettes && R CMD Sweave --engine=knitr::knitr --pdf "OUTRIDER.Rnw"

after_success:
  - Rscript -e 'covr::codecov()'

