language: r
sudo: required
dist: trusty
cache:
  - directories:
    - $HOME/python-env-OUTRIDER
    - $HOME/R/Library
    - $HOME/.cache/pip
matrix:
  include:
    - r: bioc-release
    - r: bioc-devel

addons:
  apt:
    packages:
      - libxml2-dev
      - python3.4-venv
      - python3-pip

before_install:
  - tlmgr install index
  - python3 -m venv --clear ~/python-env-OUTRIDER
  - source ~/python-env-OUTRIDER/bin/activate
  - pip install --upgrade pip

install:
  - pip install --upgrade "git+https://github.com/gagneurlab/autoCorrection.git@master"
  - R -e "install.packages('devtools', repos='http://cran.rstudio.com/')"
  - R -e "source('https://bioconductor.org/biocLite.R'); biocLite('BiocInstaller')"
  - R -e "BiocInstaller::biocLite(c('covr', 'BiocCheck'))"
  - R -e "BiocInstaller::biocLite('DESeq2')"
#  - R -e 'devtools::install_deps(dependencies=TRUE, threads=4)'
#  - R -e 'devtools::install()'

script:
  - echo 'hello world'
#  - R CMD build --no-build-vignettes .
#  - R CMD BiocCheck --new-package --no-check-vignettes *tar.gz
#  - travis_wait R CMD check --no-vignettes --timings *tar.gz
#  - travis_wait R CMD Sweave --engine=knitr::knitr --pdf "./vignettes/OUTRIDER.Rnw"

after_success:
  - Rscript -e 'covr::codecov()'

