language: r
sudo: required
dist: xenial
cache:
  - directories:
    - $HOME/R/Library

addons:
  apt:
    packages:
      - libxml2-dev
      - tk-dev
      - libgit2-dev

r:
  - bioc-devel
  - bioc-release
  - 3.5.0
  - 3.4.4
  - 3.4.2

stages:
  - Setup Cache
  - Test

# setup cache first
jobs:
  include:
    - stage: Setup Cache
      r: bioc-devel
      install: Rscript setupEnv.R
      script: true
    - stage: Setup Cache
      r: bioc-release
      install: Rscript setupEnv.R
      script: true
    - stage: Setup Cache
      r: 3.5.0
      install: Rscript setupEnv.R
      script: true
    - stage: Setup Cache
      r: 3.4.4
      install: Rscript setupEnv.R
      script: true
    - stage: Setup Cache
      r: 3.4.2
      install: Rscript setupEnv.R
      script: true

before_install:
  - tlmgr install index marginfix bera nowidow parnotes
  
install:
  - R --version
  - Rscript setupEnv.R 

script:
  - R CMD build .
  - R CMD BiocCheck --new-package --no-check-vignettes *tar.gz
  - R CMD check --no-vignettes --timings *tar.gz
  - R -e 'devtools::run_examples()'
  - cd vignettes && R CMD Sweave --engine=knitr::knitr --pdf OUTRIDER.Rnw
  
after_success:
  - Rscript -e 'covr::codecov()'

