language: r
sudo: required
dist: xenial
cache:
  - directories:
    - $HOME/R/Library

matrix:
  include:
    - r: bioc-release
    - r: bioc-devel
    - r: 3.5.0
    - r: 3.4.4
    - r: 3.4.2

addons:
  apt:
    packages:
      - libxml2-dev
      - tk-dev

before_install:
  - tlmgr install index marginfix bera nowidow parnotes

install:
  - R --version
  - R -e '
      if(0 < compareVersion("3.5.0", paste(R.Version()[c("major", "minor")], collapse="."))){
          if(isFALSE(requireNamespace("BiocInstaller"))){
              source("https://bioconductor.org/biocLite.R")
              biocLite(c("BiocInstaller"), Ncpus=6)
          }
          INSTALL <- BiocInstaller::biocLite
      } else {
          if(isFALSE(requireNamespace("BiocInstaller"))){
              install.packages("BiocManager", Ncpus=6)
          }
          INSTALL <- BiocManager::install
      }
      for(p in c("devtools", "covr", "roxygen2", "BiocCheck", "R.utils")){
          if(isFALSE(requireNamespace(p, quietly=TRUE))){
              INSTALL(p, Ncpus=6)
          }
      }
      R.utils::withTimeout(timeout=2400, {
          INSTALL(ask=FALSE, Ncpus=6)
          devtools::install(".", ask=FALSE, dependencies=TRUE, upgrade=TRUE)
      })'


script:
  - R CMD build .
  - R CMD BiocCheck --new-package --no-check-vignettes *tar.gz
  - R CMD check --no-vignettes --timings *tar.gz
#  - R -e 'devtools::run_examples()'
#  - cd vignettes && R CMD Sweave --engine=knitr::knitr --pdf "OUTRIDER.Rnw"

after_success:
  - Rscript -e 'covr::codecov()'

