language: r
cache:
  - packages
  - pip
sudo: required
dist: trusty

matrix:
  include:
    - r: bioc-release
    - r: bioc-devel

addons:
  apt:
    packages:
      - libxml2-dev
      - python3.4-venv
      - python3-pip

before_install:
  - tlmgr install index
  - python3 -m venv ~/python-env-OUTRIDER
  - source ~/python-env-OUTRIDER/bin/activate
  - pip install --upgrade pip
  - pip install --upgrade "git+https://github.com/gagneurlab/autoCorrection.git@master"

install:
  - R -e "install.packages('devtools', repos='http://cran.rstudio.com/')"
  - R -e "source('https://bioconductor.org/biocLite.R'); biocLite('BiocInstaller')"
  - R -e "BiocInstaller::biocLite(c('covr', 'BiocCheck'))"
  - R -e 'devtools::install_deps(dependencies=TRUE, threads=4)'
  - R -e 'devtools::install()'

script:
  - R CMD build --no-build-vignettes .
  - R CMD BiocCheck --new-package --no-check-vignettes *tar.gz
  - Rscript -e "library('OUTRIDER'); covr::package_coverage('.')"
  - travis_wait R CMD check --no-vignettes --timings *tar.gz
#  - travis_wait R CMD Sweave --engine=knitr::knitr --pdf "./vignettes/OUTRIDER.Rnw"

